//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
//
// File: /Volumes/Xcode/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/XCTest.framework/Versions/A/XCTest
// UUID: 98A2F926-5EF3-3A56-B307-A92C6F1B9BC2
//
//                           Arch: x86_64
//                Current version: 7503.0.0
//          Compatibility version: 1.0.0
//                 Source version: 7503.0.0.0.0
//       Minimum Mac OS X version: 10.9.0
//                    SDK version: 10.10.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @loader_path/../../../../../../../../../SharedFrameworks/
//                               = /Volumes/Xcode/Xcode.app/Contents/SharedFrameworks
//
