//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
//
// File: /Applications/Xcode-Beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/XCTest.framework/Versions/A/XCTest
// UUID: AA71A0D6-8421-3B6F-9CEF-CFB7F936F16F
//
//                           Arch: x86_64
//                Current version: 6700.0.0
//          Compatibility version: 1.0.0
//                 Source version: 6700.0.0.0.0
//       Minimum Mac OS X version: 10.9.0
//                    SDK version: 10.10.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @loader_path/../../../../../../../../../SharedFrameworks/
//                               = /Applications/Xcode-Beta.app/Contents/SharedFrameworks
//

@interface XCTestEventGenerator : NSObject
{
}

+ (id)eventDispatchQueue;
+ (struct __CGEventSource *)eventSource;
+ (id)sharedTestEventGenerator;
- (void)clickAndDragFromPoint:(struct CGPoint)arg1 toPoint:(struct CGPoint)arg2;
- (void)_startEventSequenceWithIdentifier:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (void)_scheduleCallback:(CDUnknownBlockType)arg1 afterInterface:(double)arg2;
- (void)hitKey:(unsigned short)arg1;
- (void)rightClickAtPoint:(struct CGPoint)arg1;
- (void)doubleClickAtPoint:(struct CGPoint)arg1;
- (void)clickAtPoint:(struct CGPoint)arg1;
- (void)_clickMouseButton:(unsigned int)arg1 withCount:(unsigned long long)arg2 atPoint:(struct CGPoint)arg3;
- (void)_moveMouseToPoint:(struct CGPoint)arg1;
- (struct CGRect)frameForViewInGlobalCoordinates:(id)arg1;
- (struct CGRect)globalCoordinatesForRect:(struct CGRect)arg1 inView:(id)arg2;

@end
