//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
//
// File: /Applications/Xcode-Beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks/XCTest.framework/Versions/A/XCTest
// UUID: AA71A0D6-8421-3B6F-9CEF-CFB7F936F16F
//
//                           Arch: x86_64
//                Current version: 6700.0.0
//          Compatibility version: 1.0.0
//                 Source version: 6700.0.0.0.0
//       Minimum Mac OS X version: 10.9.0
//                    SDK version: 10.10.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: @loader_path/../../../../../../../../../SharedFrameworks/
//                               = /Applications/Xcode-Beta.app/Contents/SharedFrameworks
//

@protocol XCTestObservation <NSObject>

@optional
- (void)testCaseDidFail:(XCTestRun *)arg1 withDescription:(NSString *)arg2 inFile:(NSString *)arg3 atLine:(unsigned long long)arg4;
- (void)testCaseDidStop:(XCTestRun *)arg1;
- (void)testCaseDidStart:(XCTestRun *)arg1;
- (void)testSuiteDidFail:(XCTestRun *)arg1 withDescription:(NSString *)arg2 inFile:(NSString *)arg3 atLine:(unsigned long long)arg4;
- (void)testSuiteDidStop:(XCTestRun *)arg1;
- (void)testSuiteDidStart:(XCTestRun *)arg1;
- (void)stopObserving;
- (void)startObserving;
@end
