//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (XCTestAdditions)
- (id)xct_arrayByApplyingBlock:(CDUnknownBlockType)arg1;
- (id)xct_objectsPassingTest:(CDUnknownBlockType)arg1;
@end

