//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTest/XCTestCase.h>

@interface XCTestCase (XCTestCase_RuntimeAdditions)
+ (id)xct_allTestMethodInvocations;
+ (id)xct_testMethodInvocations;
+ (id)xct_allSubclasses;
@end

