//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTest/XCTest.h>

@class NSMutableArray, NSString;

@interface XCTestSuite : XCTest
{
    NSString *name;
    NSMutableArray *tests;
}

+ (id)defaultTestSuite;
+ (id)allTests;
+ (id)structuredTests;
+ (id)testSuiteForTestCaseClass:(Class)arg1;
+ (id)testSuiteForTestCaseWithName:(id)arg1;
+ (id)testSuiteForBundlePath:(id)arg1;
+ (id)suiteForBundleCache;
+ (void)invalidateCache;
+ (id)_suiteForBundleCache;
+ (id)emptyTestSuiteNamedFromPath:(id)arg1;
+ (id)testSuiteWithName:(id)arg1;
- (void)performTest:(id)arg1;
- (Class)testRunClass;
- (unsigned long long)testCaseCount;
- (id)tests;
- (void)addTestsEnumeratedBy:(id)arg1;
- (void)addTest:(id)arg1;
- (id)description;
- (id)name;
- (void)dealloc;
- (id)initWithName:(id)arg1;

@end

