//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DTXConnection;

@interface XCTRunnerDTServiceHubSession : NSObject
{
    DTXConnection *_dtxConnection;
}

+ (id)sharedSession;
@property(readonly) DTXConnection *dtxConnection; // @synthesize dtxConnection=_dtxConnection;
- (void).cxx_destruct;
- (id)initWithConnection:(id)arg1;

@end

