//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SenTestObserver : NSObject
{
}

+ (void)addTestObserver:(Class)arg1;
+ (void)removeTestObserver:(Class)arg1;
+ (void)resumeObservation;
+ (void)suspendObservation;
+ (void)initialize;
+ (void)testSuiteDidStart:(id)arg1;
+ (void)testSuiteDidStop:(id)arg1;
+ (void)testCaseDidStart:(id)arg1;
+ (void)testCaseDidStop:(id)arg1;
+ (void)testCaseDidFail:(id)arg1;

@end

