//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XCTestObserver : NSObject
{
}

+ (void)initialize;
+ (void)suspendObservation;
+ (void)resumeObservation;
+ (void)tearDownTestObservers;
+ (void)setUpTestObservers;
+ (void)removeTestObserverClass:(Class)arg1;
+ (void)addTestObserverClass:(Class)arg1;
- (void)testCaseDidFail:(id)arg1 withDescription:(id)arg2 inFile:(id)arg3 atLine:(unsigned long long)arg4;
- (void)testCaseDidStop:(id)arg1;
- (void)testCaseDidStart:(id)arg1;
- (void)testSuiteDidStop:(id)arg1;
- (void)testSuiteDidStart:(id)arg1;
- (void)_testCaseDidFail:(id)arg1;
- (void)_testCaseDidStop:(id)arg1;
- (void)_testCaseDidStart:(id)arg1;
- (void)_testSuiteDidStop:(id)arg1;
- (void)_testSuiteDidStart:(id)arg1;
- (void)stopObserving;
- (void)startObserving;

@end

