//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XCTest;

@interface XCTestRun : NSObject
{
    double startDate;
    double stopDate;
    XCTest *test;
}

+ (id)testRunWithTest:(id)arg1;
- (id)description;
- (BOOL)hasSucceeded;
- (unsigned long long)testCaseCount;
- (unsigned long long)unexpectedExceptionCount;
- (unsigned long long)failureCount;
- (unsigned long long)totalFailureCount;
- (void)stop;
- (void)start;
- (id)stopDate;
- (id)startDate;
- (double)testDuration;
- (double)totalDuration;
- (id)test;
- (void)dealloc;
- (id)initWithTest:(id)arg1;

@end

