//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, XCAccessibilityElement;

@protocol XCUIAXNotificationHandling <NSObject>
@property(readonly) BOOL axNotificationsIncludeElement;
- (void)handleAccessibilityNotification:(int)arg1 fromElement:(XCAccessibilityElement *)arg2 payload:(NSData *)arg3;
@end

