//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTest/XCUIApplicationMonitor.h>

@class XCUILaunchServicesMonitor;

@interface XCUIApplicationMonitor_macOS : XCUIApplicationMonitor
{
    XCUILaunchServicesMonitor *_launchServicesMonitor;
}

@property(retain) XCUILaunchServicesMonitor *launchServicesMonitor; // @synthesize launchServicesMonitor=_launchServicesMonitor;
- (void).cxx_destruct;
- (void)_terminateApplicationProcess:(id)arg1;
- (id)monitoredApplicationWithProcessIdentifier:(int)arg1;
- (void)_beginMonitoringApplication:(id)arg1;
- (id)init;
- (void)dealloc;

@end

