//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol XCUITextInputSource <NSObject>
@property(readonly) NSArray *keyMaps;
@property(readonly) NSString *identifier;
- (BOOL)isEqualToInputSource:(id <XCUITextInputSource>)arg1;
- (BOOL)overrideCurrentKeyboardLayoutWithError:(id *)arg1;
- (BOOL)selectWithError:(id *)arg1;
- (BOOL)enableWithError:(id *)arg1;
@end

