//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <XCTest/XCUIRecorder_iOS.h>

@interface XCUIRecorder_tvOS : XCUIRecorder_iOS
{
}

- (id)_XCT_recordedEventNames:(id)arg1 duration:(id)arg2 startLocation:(id)arg3 startElementSnapshot:(id)arg4 startApplicationSnapshot:(id)arg5 endLocation:(id)arg6 endElementSnapshot:(id)arg7 endApplicationSnapshot:(id)arg8;
- (id)_remoteButtonSymbolNameForEventTypeSymbolName;
- (unsigned long long)platform;
- (id)defaultAttributes;

@end

