//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XCUIScreenshotProviding.h"

@class NSString;

@interface XCUIScreen : NSObject <XCUIScreenshotProviding>
{
    BOOL _isMainScreen;
    int _displayID;
}

+ (id)screens;
+ (id)mainScreen;
@property(readonly) BOOL isMainScreen; // @synthesize isMainScreen=_isMainScreen;
@property(readonly) int displayID; // @synthesize displayID=_displayID;
- (id)_legacy_macOS_screenshotDataForQuality:(long long)arg1 rect:(struct CGRect)arg2;
- (id)_screenshotDataForQuality:(long long)arg1 rect:(struct CGRect)arg2 error:(id *)arg3;
- (id)screenshotDataForQuality:(long long)arg1 rect:(struct CGRect)arg2 error:(id *)arg3;
- (id)screenshotDataForQuality:(long long)arg1 rect:(struct CGRect)arg2;
- (id)_modernScreenshotDataForQuality:(long long)arg1 rect:(struct CGRect)arg2 error:(id *)arg3;
- (id)screenshot;
- (id)_imageFromData:(id)arg1;
- (double)scale;
@property(readonly, copy) NSString *description;
- (id)initWithDisplayID:(int)arg1 isMainScreen:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

