//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, XCAXManager_OSX, XCAccessibilityElement, XCApplicationMonitor, XCUIApplicationImpl;

@interface XCUIApplicationProcess : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    BOOL _accessibilityActive;
    unsigned long long _applicationState;
    int _processID;
    id _token;
    BOOL _eventLoopHasIdled;
    BOOL _hasReceivedEventLoopHasIdled;
    BOOL _animationsHaveFinished;
    BOOL _hasReceivedAnimationsHaveFinished;
    XCUIApplicationImpl *_applicationImplementation;
    long long _activationPolicy;
    id <XCTestManager_IDEInterface> _IDEProxy;
    XCApplicationMonitor *_applicationMonitor;
    XCAXManager_OSX *_AXManager_OSX;
}

@property XCAXManager_OSX *AXManager_OSX; // @synthesize AXManager_OSX=_AXManager_OSX;
@property XCApplicationMonitor *applicationMonitor; // @synthesize applicationMonitor=_applicationMonitor;
@property id <XCTestManager_IDEInterface> IDEProxy; // @synthesize IDEProxy=_IDEProxy;
@property(nonatomic) long long activationPolicy; // @synthesize activationPolicy=_activationPolicy;
@property XCUIApplicationImpl *applicationImplementation; // @synthesize applicationImplementation=_applicationImplementation;
- (void)terminate;
- (void)_handleAXNotification:(id)arg1 info:(id)arg2;
- (void)waitForQuiescence;
@property BOOL hasReceivedAnimationsHaveFinished;
@property BOOL animationsHaveFinished;
@property BOOL hasReceivedEventLoopHasIdled;
@property BOOL eventLoopHasIdled;
@property(retain) id token;
@property(nonatomic) int processID;
@property(nonatomic) unsigned long long applicationState;
@property(nonatomic) BOOL accessibilityActive;
@property(readonly, copy) XCAccessibilityElement *accessibilityElement;
- (id)description;
- (id)init;
- (id)initWithApplicationMonitor:(id)arg1 AXInterface:(id)arg2 IDEProxy:(id)arg3;
- (void)dealloc;

@end

