//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSInvocation.h"

@interface NSInvocation (SenTesting)
+ (id)testMethodPrefix;
+ (void)setTestMethodPrefix:(id)arg1;
- (id)testMethodPrefix;
- (BOOL)isReturningVoid;
- (BOOL)hasTestPrefix;
- (unsigned int)numberOfParameters;
- (BOOL)hasTestCaseSignature;
- (int)compare:(id)arg1;
@end

