//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SenTestingKit/SenTestRun.h>

@class NSMutableArray;

@interface SenTestSuiteRun : SenTestRun
{
    NSMutableArray *runs;
}

- (id)initWithTest:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)start;
- (void)stop;
- (id)testRuns;
- (void)addTestRun:(id)arg1;
- (unsigned int)failureCount;
- (unsigned int)unexpectedExceptionCount;
- (double)testDuration;

@end

