//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class SenTest;

@interface SenTestRun : NSObject <NSCoding>
{
    double startDate;
    double stopDate;
    SenTest *test;
}

+ (id)testRunWithTest:(id)arg1;
- (id)initWithTest:(id)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)test;
- (double)totalDuration;
- (double)testDuration;
- (id)startDate;
- (id)stopDate;
- (void)start;
- (void)stop;
- (unsigned int)totalFailureCount;
- (unsigned int)failureCount;
- (unsigned int)unexpectedExceptionCount;
- (unsigned int)testCaseCount;
- (BOOL)hasSucceeded;
- (void)postNotificationName:(id)arg1 userInfo:(id)arg2;
- (void)postNotificationName:(id)arg1;
- (id)description;

@end

