//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <SenTestingKit/SenTest.h>

#import "NSCoding.h"

@class NSInvocation, SenTestCaseRun;

@interface SenTestCase : SenTest <NSCoding>
{
    NSInvocation *invocation;
    SenTestCaseRun *run;
    SEL failureAction;
}

+ (id)testCaseWithInvocation:(id)arg1;
+ (id)testCaseWithSelector:(SEL)arg1;
+ (BOOL)isInheritingTestCases;
+ (id)testInvocations;
- (id)init;
- (id)initWithInvocation:(id)arg1;
- (id)initWithSelector:(SEL)arg1;
- (Class)classForCoder;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (SEL)selector;
- (unsigned int)testCaseCount;
- (id)name;
- (id)description;
- (void)dealloc;
- (id)invocation;
- (void)setInvocation:(id)arg1;
- (SEL)failureAction;
- (void)setFailureAction:(SEL)arg1;
- (void)continueAfterFailure;
- (void)raiseAfterFailure;
- (void)logException:(id)arg1;
- (void)raiseException:(id)arg1;
- (void)failWithException:(id)arg1;
- (Class)testRunClass;
- (void)invokeTest;
- (void)performTest:(id)arg1;
- (void)setUpTestWithSelector:(SEL)arg1;
- (void)tearDownTestWithSelector:(SEL)arg1;
- (void)beforeTestIteration:(unsigned int)arg1 selector:(SEL)arg2;
- (void)afterTestIteration:(unsigned int)arg1 selector:(SEL)arg2;
- (unsigned int)numberOfTestIterationsForTestWithSelector:(SEL)arg1;

@end

