//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSEnumerator.h"

@class NSMutableArray;

@interface SenTestClassEnumerator : NSEnumerator
{
    NSMutableArray *classes;
    int currentIndex;
    BOOL isAtEnd;
}

+ (id)classEnumerator;
- (id)rejectedClassNames;
- (BOOL)isValidClass:(Class)arg1;
- (id)init;
- (id)nextObject;
- (void)dealloc;

@end

