//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SenClassWrapper : NSObject
{
    Class _wrappedClass;
}

- (Class)wrappedClass;
- (id)initWithWrappedClass:(Class)arg1;

@end

